### ISSUE TITLE
Cast Plugin Not Found

### ISSUE THREAD

**Issue by Gregy77** [d8ahazard/Cast.bundle#9]
Hi, I am having issues getting Flex to talk with the cast plugin.  I have installed the cast plugin under plex and can see it enabled in plex.  Even under plex I can do a scan and see it update devices.

However on the web page front end for Flex I am unable to see any devices to cast to and if I select rescan I get the "Cast Plugin not Found".

Any help would be appreciated.

**Comment by bestballer** [comment]
hey there.  

i had the same issue with my phlex.    i deleted the cast.bundle that was in plug-in folder that i had previously installed.     then i installed webtools plex plug in.   and added the plex git hub url to webtools. and that fixed my problems

**Comment by d8ahazard** [comment]
I should probably mention that I've pushed updates that improve the
reliability of cast detection in some cases...this may have been the reason
why re-installing with Webtools seemed to magically fix it...

**Comment by Gregy77** [comment]
Thanks Bestballer, tried that and no go still.

**Comment by LoudSoftware** [comment]
Same thing here, with manual install and webtools install still doesn't work

**Comment by Fluxenator** [comment]
Same issue here, my plex logs are listed below. Is there a way to manually add cast devices?
Plex version: 1.14.0.5470
Running Ubuntu Server 18.04.1

2018-12-07 09:47:05,514 (7efc0f7fe700) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Cast.bundle/Contents/Code/__init__.py", line 204, in Resources
    casts = fetch_devices()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Cast.bundle/Contents/Code/__init__.py", line 646, in fetch_devices
    req.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1217, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1190, in do_open
    r = h.getresponse()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/httplib_new.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/httplib_new.py", line 431, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/httplib_new.py", line 395, in _read_status
    raise BadStatusLine(line)
BadStatusLine

**Comment by d8ahazard** [comment]
All...

Try out https://github.com/d8ahazard/FlexTV.bundle

**Comment by CDKrash** [comment]
Hello all,

Tried installing and running locally and it doesn't even see the plugin. Rolled back the server from a week ago backup and get the error that the plugin is out of date from the hosted site. Did all the normal steps, Uninstall, re-download, reinstall everything and I am still getting the error. Even tried older versions and sifting though Github and trying anything I could find, nadda.. Everything worked for 2 days, then just stopped. Don't know what got updated.

I have tried all of the above options and I am getting the "Plugin out of date" from the hosted site.  And "Plugin not found" from Self-hosted. Any help would be GREATLY appreciated!!

![image](https://user-images.githubusercontent.com/45719888/49689784-f3d6cf80-faeb-11e8-9be1-3943290c123c.png)

![image](https://user-images.githubusercontent.com/45719888/49689835-b757a380-faec-11e8-97b1-a42e1e2a2aa4.png)


Edit #2: I deleted everything from the Plugin Support folder for Cast and any plug in related. I also deleted WebTools info from the Plugin Support folder and then restarted Plex. No plugins were showing not even WebTools. Logged into the WebTools web interface and hit "Migrate"... I don't know how or why, but that worked!!! 

I am now able to play Plex and connect to all devices from Phlex (Local Install).... I don't know how or why.. Just glad it is!! Granted it still pops up with "Your Cast Plugin is out of date" and shows me nothing on the interface for previous commands. But at least I can use Plex through Google home and cast to my devices.

Bug report.. lol
 

Edit #3 Sadly the issue has returned. Same error “Cast Plugin out-of-date” and can’t see any devices. This would be a great thing if it was solid.. Please let me know if there are any developments in the plugin issue.... Until then, I guess I go without. I am at my wits end troubleshooting this.

Edit #4: Deleted the Cast.bundle from the Plugin folder again. Used the FlexTV.bundle and put the FlexTV.bundle in the folder and then "Migrated" the plugins again from the WebTools website. I have done this before many times and it never worked. I don't know why, but it IS working now. I am able to talk to my Plex server and cast to all of my devices. Now.... Let's see how long this lasts, 24 hours so far.

**Comment by akanter** [comment]
I'm getting that same "Cast plugin not found!" message using both Cast.bundle and FlexTV.bundle. I've tried installing via WebTools and still no luck.

While in Plex, I can see that the plugin is loaded and I can even show my two Google Home devices listed, but the Phlex App cannot seem to see them in the dropdown list (and I'm getting that annoying message).

<img width="779" alt="screenshot 2018-12-24 18 17 17" src="https://user-images.githubusercontent.com/1119631/50409552-4f6db200-07a8-11e9-93a8-ae0f6c548739.png">

From my devhost's CLI
```
>curl "http://127.0.1.1:32400/chromecast/devices?X-Plex-Token=TOKEN"

<MediaContainer size="2" version="1.1.106"><Device status="True" name="Kitchen display" uri="192.168.1.249:8009" type="cast" id="192.168.1.249:8009"/>
<Device status="True" name="Alex & Sarah Speaker" uri="192.168.1.168:8009" type="audio" id="192.168.1.168:8009"/></MediaContainer>

```
 (which seems correct)

When I hit the rescan button in the Phlex app, I can see in the plugin logs that the plugin sees the request:

#1831 | 2018-12-24 18:38:47,355 (7fd780ff9700) : DEBUG (runtime:717) - Handling request GET /chromecast/clients
-- | --
#1832 | 2018-12-24 18:38:47,359 (7fd780ff9700) : DEBUG (runtime:814) - Found route matching /chromecast/clients
#1833 | 2018-12-24 18:38:47,359 (7fd780ff9700) : DEBUG (__init__:285) - Recieved a call to fetch all devices
#1834 | 2018-12-24 18:38:47,360 (7fd780ff9700) : DEBUG (__init__:1237) - Returning cached data
#1835 | 2018-12-24 18:38:47,361 (7fd780ff9700) : DEBUG (__init__:1243) - Header key Host is 192.168.1.65:32400
#1836 | 2018-12-24 18:38:47,362 (7fd780ff9700) : DEBUG (__init__:1243) - Header key X-Plex-Token is TOKEN
#1837 | 2018-12-24 18:38:47,362 (7fd780ff9700) : DEBUG (__init__:1245) - We have a Token
#1838 | 2018-12-24 18:38:47,363 (7fd780ff9700) : DEBUG (__init__:1243) - Header key Accept-Encoding is gzip
#1839 | 2018-12-24 18:38:47,363 (7fd780ff9700) : DEBUG (__init__:1243) - Header key Accept is */*
#1840 | 2018-12-24 18:38:47,364 (7fd780ff9700) : DEBUG (__init__:1243) - Header key User-Agent is Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
#1841 | 2018-12-24 18:38:47,364 (7fd780ff9700) : DEBUG (__init__:1263) - Gonna connect to http://127.0.1.1:32400/clients?X-Plex-Token=TOKEN
#1842 | 2018-12-24 18:38:47,368 (7fd780ff9700) : DEBUG (networking:166) - Requesting 'http://127.0.1.1:32400/clients?X-Plex-Token=TOKEN'
#1843 | 2018-12-24 18:38:47,379 (7fd780ff9700) : DEBUG (runtime:88) - Sending packed state data (107 bytes)
#1844 | 2018-12-24 18:38:47,380 (7fd780ff9700) : DEBUG (runtime:924) - Response: [200] FlexContainer, 282 bytes

Any idea what the issue might be?

**Comment by dony71** [comment]
same problem here, plugin not detected on synology devices
debug log shows below :

2019-03-26 17:18:40,907 (-490f7000) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 782228f (Wed Mar 13 14:41:55 UTC 2019)
2019-03-26 17:18:40,959 (-490f7000) :  DEBUG (core:361) - Using the elevated policy
2019-03-26 17:18:40,960 (-490f7000) :  DEBUG (core:450) - Starting runtime component.
2019-03-26 17:18:40,995 (-490f7000) :  DEBUG (core:450) - Starting caching component.
2019-03-26 17:18:40,996 (-490f7000) :  DEBUG (core:450) - Starting data component.
2019-03-26 17:18:40,997 (-490f7000) :  DEBUG (core:450) - Starting networking component.
2019-03-26 17:18:41,045 (-490f7000) :  DEBUG (networking:284) - Loaded HTTP cookies
2019-03-26 17:18:41,080 (-490f7000) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2019-03-26 17:18:41,111 (-490f7000) :  DEBUG (core:450) - Starting localization component.
2019-03-26 17:18:41,115 (-490f7000) :  INFO (localization:409) - Setting the default locale to en-us
2019-03-26 17:18:41,116 (-490f7000) :  DEBUG (core:450) - Starting messaging component.
2019-03-26 17:18:41,123 (-4f998ba0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.Cast'
2019-03-26 17:18:41,158 (-490f7000) :  DEBUG (core:450) - Starting debugging component.
2019-03-26 17:18:41,159 (-490f7000) :  DEBUG (core:450) - Starting services component.
2019-03-26 17:18:41,159 (-490f7000) :  DEBUG (core:450) - Starting myplex component.
2019-03-26 17:18:41,160 (-490f7000) :  DEBUG (core:450) - Starting notifications component.
2019-03-26 17:18:43,672 (-490f7000) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.Cast in namespace 'metadata'
2019-03-26 17:18:43,737 (-490f7000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2019-03-26 17:18:44,628 (-5039cba0) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2019-03-26 17:18:44,630 (-5039cba0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2019-03-26 17:18:44,636 (-490f7000) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2019-03-26 17:18:44,652 (-51724ba0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2019-03-26 17:18:44,659 (-490f7000) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2019-03-26 17:18:44,659 (-490f7000) :  DEBUG (core:150) - Finished starting framework core
2019-03-26 17:18:44,660 (-490f7000) :  DEBUG (core:560) - Loading plug-in code
2019-03-26 17:18:44,730 (-51724ba0) :  DEBUG (core:538) - Machine identifier is 34190b563d2e6494424eda23ee6d73d0555c645b
2019-03-26 17:18:44,731 (-51724ba0) :  DEBUG (core:539) - Server version is 1.15.2.793-782228f99
2019-03-26 17:18:48,030 (-490f7000) :  DEBUG (core:566) - Finished loading plug-in code
2019-03-26 17:18:54,659 (-5039cba0) :  DEBUG (services:362) - Loaded services
2019-03-26 17:18:54,680 (-50d60ba0) :  DEBUG (services:438) - No shared code to load
2019-03-26 17:18:54,684 (-490f7000) :  CRITICAL (core:615) - Exception starting plug-in (most recent call last):
  File "/i-data/0044c7f4/.PKG/PlexMediaServer/share/PlexMediaServer/home/Resources/Plug-ins-782228f99/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/i-data/0044c7f4/.PKG/PlexMediaServer/share/PlexMediaServer/home/Resources/Plug-ins-782228f99/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/i-data/0044c7f4/.PKG/PlexMediaServer/share/PlexMediaServer/lib/Plex Media Server/Plug-ins/Cast.bundle/Contents/Code/__init__.py", line 22, in <module>
    import pychromecast
  File "/i-data/0044c7f4/.PKG/PlexMediaServer/share/PlexMediaServer/home/Resources/Plug-ins-782228f99/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
ImportError: No module named _ctypes

**Comment by rpirsc13** [comment]
Same problem. It seems that the plugin is not compatible with the latest plex build.

```2019-05-02 00:04:40,882 (7583c600) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: bb4a2cb (Mon Apr 22 16:54:03 UTC 2019)
2019-05-02 00:04:40,882 (7583c600) :  DEBUG (core:361) - Using the elevated policy
2019-05-02 00:04:40,883 (7583c600) :  DEBUG (core:450) - Starting runtime component.
2019-05-02 00:04:40,887 (7583c600) :  DEBUG (core:450) - Starting caching component.
2019-05-02 00:04:40,888 (7583c600) :  DEBUG (core:450) - Starting data component.
2019-05-02 00:04:40,889 (7583c600) :  DEBUG (core:450) - Starting networking component.
2019-05-02 00:04:40,889 (7583c600) :  DEBUG (networking:288) - No cookie jar found
2019-05-02 00:04:40,891 (7583c600) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2019-05-02 00:04:40,893 (7583c600) :  DEBUG (core:450) - Starting localization component.
2019-05-02 00:04:40,894 (7583c600) :  INFO (localization:409) - Setting the default locale to en-us
2019-05-02 00:04:40,894 (7583c600) :  DEBUG (core:450) - Starting messaging component.
2019-05-02 00:04:40,897 (7583c600) :  DEBUG (core:450) - Starting debugging component.
2019-05-02 00:04:40,898 (7583c600) :  DEBUG (core:450) - Starting services component.
2019-05-02 00:04:40,899 (7583c600) :  DEBUG (core:450) - Starting myplex component.
2019-05-02 00:04:40,899 (6f0f7460) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.FlexTV'
2019-05-02 00:04:40,899 (7583c600) :  DEBUG (core:450) - Starting notifications component.
2019-05-02 00:04:41,475 (7583c600) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.FlexTV in namespace 'metadata'
2019-05-02 00:04:41,493 (7583c600) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2019-05-02 00:04:41,551 (7583c600) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2019-05-02 00:04:41,551 (6f0f7460) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2019-05-02 00:04:41,553 (6f0f7460) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/xxxxxxxxx'
2019-05-02 00:04:41,557 (7583c600) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2019-05-02 00:04:41,559 (7583c600) :  DEBUG (core:150) - Finished starting framework core
2019-05-02 00:04:41,559 (6e0e7460) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2019-05-02 00:04:41,560 (7583c600) :  DEBUG (core:560) - Loading plug-in code
2019-05-02 00:04:43,154 (6e0e7460) :  DEBUG (core:538) - Machine identifier is xxxx
2019-05-02 00:04:43,162 (6e0e7460) :  DEBUG (core:539) - Server version is 1.15.4.993-bb4a2cb6c
2019-05-02 00:04:44,301 (6f0f7460) :  DEBUG (services:362) - Loaded services
2019-05-02 00:04:44,410 (6e8ef460) :  DEBUG (services:438) - No shared code to load
2019-05-02 00:04:45,068 (7583c600) :  DEBUG (core:566) - Finished loading plug-in code
2019-05-02 00:04:46,223 (7583c600) :  CRITICAL (core:615) - Exception starting plug-in (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-bb4a2cb6c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 608, in start
    self.sandbox.execute(self.init_code)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-bb4a2cb6c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 256, in execute
    exec(code) in self.environment
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/FlexTV.bundle/Contents/Code/__init__.py", line 25, in <module>
    import pychromecast
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-bb4a2cb6c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 345, in __import__
    raise e
ImportError: No module named _ctypes
```

**Comment by d8ahazard** [comment]
Hey all...please check out https://github.com/FlexTV.bundle for the latest iteration of the plugin.

Also, there's an experimental stand-alone app for homes without a PMS server, but you want to control cast devices at https://github.com/d8ahazard/FlexConnect - and docker - https://github.com/d8ahazard/docker-FlexConnect

If you have issues, feel free to report them there!
